name: Chrono Cross (USA)
sha1: 26c3da2599af76f7e352b8594d048b527d6bd0d9
options:
  basename: slps_023.64
  target_path: disc/extracted/prog/slps_023.64
  elf_path: build/slps_023.64.elf
  base_path: ../
  platform: psx
  compiler: PSYQ

  asm_path: asm/slps_023.64
  src_path: src/slps_023.64
  build_path: build
  # create_asm_dependencies: True

  ld_script_path: linker/slps_023.64.ld
  ld_dependencies: True
  ld_sections_allowlist:
    - .debug_line
    - .debug_info
    - .debug_abbrev
    - .debug_aranges
    - .debug_str
    - .debug_ranges
    - .debug_loc
    - .debug_frame
    - .debug_line_str
    - .debug_rnglists
    - .debug_loclists
    - .symtab
    - .strtab
    - .shstrtab
  
  find_file_boundaries: False
  gp_value: 0x80073B70
  global_vram_start: 0x80010000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path: 
    - config/symbol_addrs.slps_023.64.txt
  reloc_addrs_path: 
    - config/reloc_addrs.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.slps_023.64.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.slps_023.64.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  migrate_rodata_to_functions: false
  data_string_guesser_level: 2

  ld_bss_is_noload: True
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    # bss_size: 0x21500
    bss_contains_common: True
    align: 4
    section_order: [".text", ".rodata", ".sdata", ".data", ".sbss", ".bss"]
    subsegments:
      - [0x00800, asm]
      - [0x008C4, asm, psyq/libc]
      - [0x01574, asm, psyq/libgpu]
      - [0x05364, asm, psyq/libpad]
      - [0x08E94, asm, psyq/libmath]
      - [0x09534, asm, psyq/libcard]
      - [0x099D4, asm]
      - [0x0CC50, asm]
      - [0x13040, asm, psyq/libapi]
      - [0x138A0, asm, psyq/libcd]
      - [0x157B0, asm, psyq/libgte]
      - [0x18050, asm, psyq/libetc]
      - [0x18D60, asm, psyq/libsn]
      - [0x18F20, asm, psyq/libspu]
      - [0x19DF0, asm]
      - [0x19DF0, asm]
      - [0x1A508, asm]
      - [0x1BD2C, asm]
      - [0x2225C, asm]
      - [0x2A200, asm]
      - [0x3A71C, c, system/soundApi]
      - [0x3B8B4, asm, psyq/libspu/SpuSetTransferStartAddr]
      - [0x3B914, c, system/spu]
      - [0x3BFF4, asm, psyq/libapi_2]
      - [0x3C164, asm, psyq/libspu2]
      - [0x3C494, c, system/sound]
      - [0x3E4B0, asm, psyq/libspu3]
      - [0x3E550, c, system/sound2]
      - [0x3F78C, c, system/soundCommand]
      - [0x41E04, asm, psyq/libspu_4]
      - [0x42644, asm, psyq/libapi_3]
      - [0x42654, asm, psyq/libspu_5]
      - [0x42664, c, system/sound3]
      - [0x44668, c, system/soundVM]
      - [0x46210, c, system/sound4]
      - [0x46B7C, asm, psyq/libspu/SpuSetIRQAddr]
      - [0x46BBC, asm]
      - [0x46C6C, rodata, psyq/libc]     # 0x8005646C
      - [0x46C8C, rodata, psyq/libgpu]   # 0x8005648C
      - [0x46EDC, rodata, psyq/libpad]   # 0x800566DC
      - [0x46EFC, rodata, psyq/libmath]  # 0x800566FC
      - [0x508E0, rodata, 99D4]          # 0x800600E0
      - [0x5983C, rodata, 19DF0]         # 0x8006903C
      - [0x599D0, rodata, CC50]
      - [0x59BE8, rodata, psyq/libcd]    # 0x800693E8
      - [0x59CE0, rodata, psyq/libetc]   # 0x800694E0
      - [0x59DA0, rodata, psyq/libspu]   # 0x800695A0
      - [0x59F04, rodata, 1A508]
      - [0x5A0A8, rodata, 1BD2C]
      - [0x5A2EC, rodata, psyq/libgte]   # 0x80069AEC
      - [0x5A914, rodata, 2225C]
      - [0x5ABB8, rodata, 2A200]
      - [0x5B0C4, rodata, psyq/libspu2]  # 0x8006A8C4
      - [0x5B0F4, rodata, system/sound3] # 0x8006A8F4
      - [0x5B290, data]   # 0x8006AA90
      # - [0x64380, bss]    # 0x80073B80
      # - [0x85898]         # 0x80095098

  - name: secondary
    type: code
    start: 0x85898 # 0x80095098
    vram: 0x80095098
    # bss_size: 0x40000 # yolo
    bss_contains_common: True
    align: 4
    section_order: [".rodata", ".text", ".sdata", ".data", ".sbss", ".bss"]
    subsegments:
      - [0x85898, rodata, 85FE4] # 0x80095098
      - [0x85CBC, rodata, 88264]
      - [0x85D30, rodata, 89B4C]
      - [0x85E7C, rodata, 92208]
      - [0x85F70, rodata, 96EB8]
      - [0x85FE4, asm]    # 0x800957E4
      - [0x88264, asm]    # 0x80097A64
      - [0x89B4C, asm]    # 0x8009934C
      - [0x92208, asm]    # 0x800A1A08
      - [0x96EB8, asm]    # 0x800A66B8
      - [0x98250, data]   # 0x800A7A50
      - [0x9A800]
