#ifndef _SPU_H
#define _SPU_H

#define SPU_DECODE_DATA_START       ( 0x0000 )
#define SPU_DECODE_DATA_SIZE        ( 0x1000 )

#define SPU_IRQ_CLEAR_BLOCK_START   SPU_DECODE_DATA_SIZE
#define SPU_IRQ_CLEAR_BLOCK_SIZE    ( 0x0010 )
#define SPU_IRQ_CLEAR_BLOCK_END     ( SPU_IRQ_CLEAR_BLOCK_START + SPU_IRQ_CLEAR_BLOCK_SIZE )

#define SPU_WAVEFORM_DATA_START     SPU_IRQ_CLEAR_BLOCK_END

#endif // _SPU_H
